### ISSUE TITLE
Xenon skins

### ISSUE THREAD

**Issue by Arthur1967** [Helly1206/hellyrepo#1]
Is there a zip file for the Zenon skins? I really liked them.

**Comment by Helly1206** [comment]
Sorry, I don't maintain the Zenon skin.
________________________________
Van: Arthur1967 ***@***.***>
Verzonden: zondag 22 januari 2023 18:31
Aan: Helly1206/hellyrepo ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [Helly1206/hellyrepo] Xenon skins (Issue #1)


Is there a zip file for the Zenon skins? I really liked them.

**Comment by Arthur1967** [comment]
OK I just thought you did because I seen your name on it when I go to
install it through digs
